// <auto-generated />
namespace Talent_Crowd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PollingC6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PollingC6));
        
        string IMigrationMetadata.Id
        {
            get { return "201502280327546_PollingC6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
